# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

# Do not build my PR twice.  Use the build on branch.
if: NOT (type == pull_request AND head_repo == tkf/SparseXX.jl)

install:
  - unset JULIA_PROJECT
  - julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
  - julia -e 'using Run; Run.prepare_test()'
script:
  - julia -e 'using Run; Run.test(inline=false)'
after_success:
  - julia -e 'using Run; Run.after_success_test()'
